"""add is_favorite to bookmarks

Revision ID: 2ca52ca167c7
Revises: c240f8864f2c
Create Date: 2026-09-19 11:48:56.097332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ca52ca167c7"
down_revision: str | Sequence[str] | None = "c240f8864f2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookmarks", sa.Column("is_favorite", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmarks", "is_favorite")
    # ### end Alembic commands ###
