"""initial bookmarks table

Revision ID: c240f8864f2c
Revises:
Create Date: 2026-09-19 11:43:19.264768

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c240f8864f2c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
